[Xamarin.Forms] Implementing IsPlaying
martijn00/LottieXamarin pull request #206
Opened 2018-12-18 11:37 UTC by jimbobbennett

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Fixes #205 

### :arrow_heading_down: What is the current behavior?

The `IsPlaying` property in the Xamarin.Forms `AnimationView` wasn't doing anything

### :new: What is the new behavior (if this is a feature change)?

The `IsPlaying` property is correctly wired up in the renderer. This also marks `AutoPlay` as obsolete as it replicates the behaviour of `IsPlaying="true"`

### :boom: Does this PR introduce a breaking change?

### :bug: Recommendations for testing

The `Example.Forms` sample project has been updated.

### :memo: Links to relevant issues/docs

#205 

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

2018-12-18 11:37 UTC, jimbobbennett commented
This is a work in progress, the code should work but I can't get the example project to build to test it.

2019-01-24 17:02 UTC, martijn00 approved these changes

2019-01-24 17:39 UTC, martijn00 requested changes
@jimbobbennett I've merged some stuff and done changes to get the Forms samples compiling again. Can you rebase your PR and check it?

2019-06-19 12:07 UTC, afk013 commented
Hi @jimbobbennett could you, when you get a moment rebase the PR please. I have been using your changes for a while now in a locally generated nuget however it would be nice to resume using the public one again especially when bringing Lottie into new projects. Thanks.

2019-06-23 19:09 UTC, martijn00 approved these changes

2019-06-23 19:09 UTC, merged